"""
Django settings for coplate_project project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'r-hb3o_ar=e9sgxo*7$-qm-^^3%l=k3fus6nj*(dmrl6bg!i6v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'coplate',
    'widget_tweaks',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware', # request에 user 속성 추가
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'coplate.middleware.ProfileSetupMiddleware',
]

ROOT_URLCONF = 'coplate_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'coplate_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'coplate.validators.CustomPasswordValidator'
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'ko'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/uploads/'

# Auth Settings

AUTH_USER_MODEL = 'coplate.User'

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_SIGNUP_REDIRECT_URL = 'profile-set'  # 회원가입 리디렉트 url 설정
LOGIN_REDIRECT_URL = 'index'  # 로그인 리디렉트 url 설정
LOGIN_URL = 'account_login' # 웹서비스 로그인에 대한 url을 설정, allauth가 제공해주는 것을 쓰고있기 때문에 account_login이라 작성
ACCOUNT_LOGOUT_ON_GET = True  # 로그아웃시 바로 나가기 위해서

# 인증방법을 email로 설정, username이 default값, 둘다 허용하고프면 username_email
ACCOUNT_AUTHENTICATION_METHOD = 'email'

# 회원가입시 이메일을 필수입력으로, 유저네임은 입력안받도록 설정(회원가입, 로그인 필드에 필수입력 설정을 True, False로 할 수 있음)
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
# ACCOUNT_SIGNUP_FORM_CLASS = 'coplate.forms.SignupForm' 

# 로그인 계정 세션 기억 설정(항상 유지할 수 있도록)
ACCOUNT_SESSION_REMEMBER = True

# 쿠키의 유효시간 설정, 기본값은 2주 설정하고 싶다면 초단위로 입력
# SESSION_COOKIE_AGE = 3600 사용안함

# 회원가입시 오류가 나도 비밀번호가 초기화 안되도록 설정
ACCOUNT_PASSWORD_INPUT_RENDER_VALUE = True

# mandatory - 이메일 인증하지 않으면 로그인 불가, optional - 이메일 인증을 하지 않아도 로그인 가능, none - 인증을 하지 않는다
# ACCOUNT_EMAIL_VARIFICATION = 'optional' # 기본값이 optional

# 이메일 인증처리
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = 'account_email_confirmation_done'
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = 'account_email_confirmation_done'
ACCOUNT_EMAIL_SUBJECT_PREFIX = ""

# 비밀번호 재설정 링크 유효기간 설정
PASSWORD_RESET_TIMEOUT_DAYS = 3


# Email settings
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # 이메일이 콘솔로 보내지도록 설정
# 구글을 통해 메일 인증 받기
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'dlrhkdghsp@gmail.com'
EMAIL_HOST_PASSWORD = 'gpnzuqydllvzhboq'