# Generated by Django 2.2.24 on 2021-09-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podomarket', '0004_auto_20210926_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default_profile_pic.jpeg', upload_to='profile_pics'),
        ),
    ]
