# Generated by Django 2.2.24 on 2021-09-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coplate', '0006_auto_20210930_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default_profile_pic.jpeg', upload_to='profile_pics'),
        ),
    ]
