# Generated by Django 2.2.24 on 2021-09-30 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coplate', '0008_auto_20210930_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
