# Generated by Django 2.2.24 on 2021-09-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coplate', '0009_remove_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default_profile_pic.jpg', upload_to='profile_pics'),
        ),
    ]
